language: node_js
sudo: required
node_js:
- 7.9.0
cache:
  directories:
  - node_modules
branches:
  only:
  - hexo
before_install:
- npm install -g hexo-cli
install:
- npm install
- npm install hexo-deployer-git --save
before_script: 
script:
- hexo clean
- hexo generate
after_script:
- git config user.name "wf2311"
- git config user.email "wf2311@163.com"
- sed -i "s/github_token/${GITHUB_TOKEN}/g" ./_config.yml
- sed -i "s/gitee_token/${GITEE_TOKEN}/g" ./_config.yml
- cat ./_config.yml
- hexo deploy
env:
  global:
    secure: rwjE4x9CTkWAMalrkiWo6ZrmnyZ1w31DIKqkOwhxJWsNrYwqL0ZqPuD0dbbcojGKgBExzeyOSttSfeLGU6w6q6yc1nFtTSFIbjMm8QiFHmQAt7aHjIKYm/s0QrGUWbqn/LPibJvRgzJWuRUk5VwlL/ftUyoX4pn6qC/4kxsu7HPb4/MGbj5PlJB42mkrWjT0TtDhb7ZqyE06Xzf7KkiSuSudo0C8XiL8XlSIO4LaUXkU5zdIzr/zrIe1zF7A4HzGfKIDM25TCtgqsgh86TIpcDnWjHIpKhayOS1ZFkn8NJLP2aOhxh9pDW+AyrvZgL9FDd9nknEN8K/Fbz37lhq7ZH/Y3Hk2fFlS54CtzNywrb/wYpOrxNEm07wOrMPGNfhXp80BLK5xW2w8r4RyKMAxCBhNdmLMIqNq5r0RnG/I0fT0UpXJ6cDCBDrwd6N5xGgW8zVSwRb0dZRoDBS7ikrN3pUMSDjhhtkqr6+xWuj2ovuErKAnlS0oTy4tbNEOIcTrNrETdXnyMgsMjxReh6fw4xPmBrAbPO+bdfGWF+EBdRLdvKY/efJoYTB2eBxsOKV+P/SZKlZW2Q2LNTQQ2CrLy7YUSIbKbYuR0H1XPy2Ot/IPjCOP9z7qAhxl/U+3y9IaetEadYNLPo8EofYRSXtIjUQF3609PRf2xDEnta/euwM=
